spring:
  datasource:
    url: jdbc:postgresql://localhost:6599/talk_tactics
    username: postgres
    password: admin
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create-drop
    #show-sql: true