package com.piotrpabich.talktactics.course;

public class CourseDataGenerator {
    private static final String[] TITLES = {
            "English Word Mastery",
            "Word Learning Journey",
            "Vocabulary Masterclass",
            "Secrets of Word Mastery",
            "Dive into English Words",
            "Explore English Vocabulary",
            "Enhance Your Vocabulary",
            "Confidence in Communication",
            "Immerse Yourself in English",
            "Achieve Vocabulary Fluency",
            "Transformative Learning",
            "Build a Strong Foundation",
            "Effortless Word Learning",
            "Elevate Your Language Skills",
            "Unleash Your Potential",
            "Robust Vocabulary Development",
            "Understanding Words in Context",
            "Empower Yourself with Words",
            "Achieve Your Learning Goals",
            "Maximize Your Learning Outcomes",
            "Improve Your Vocabulary",
            "Effective Memorization Strategies",
            "Transform Your Language Skills",
            "Expand Your Vocabulary",
            "Joy of Learning",
            "Stay Motivated and Inspired",
            "Fun and Supportive Learning",
            "Beauty of the English Language",
            "Engaging and Interactive Learning",
            "Accelerated Learning",
            "Next-Level Language Skills",
            "Practical and Engaging Learning",
            "Practical Language Skills",
            "Learn at Your Own Pace",
            "Stay Motivated and On Track",
            "Engaging and Interactive Learning",
            "Focused Learning Approach",
            "Solid Foundation in Vocabulary",
            "Expertly Designed Curriculum",
            "Personalized Learning",
            "Learn Words in Context",
            "Interactive and Engaging Materials",
            "Fluency Through Practice",
            "Immersive Learning Experience",
            "Essential Words for Conversations",
            "Confidence in Language Skills",
            "Deeper Appreciation for Language",
            "Start Your Journey Today"
    };
    private static final String[] DESCRIPTIONS = {
            "Discover a comprehensive selection of English words tailored for learners of all levels.",
            "Embark on an enriching journey through our curated English word courses.",
            "Master essential English vocabulary with our structured and engaging courses.",
            "Unlock the secrets of English word mastery with our expertly designed curriculum.",
            "Dive into the world of English vocabulary and expand your linguistic horizons.",
            "Explore a diverse range of English words and phrases to enhance your language skills.",
            "Enhance your English proficiency with our dynamic and interactive word learning courses.",
            "Gain confidence in your English communication abilities through targeted word learning.",
            "Immerse yourself in the richness of the English language with our immersive courses.",
            "Achieve fluency in English vocabulary through our systematic and effective courses.",
            "Experience a transformative learning journey with our in-depth English word courses.",
            "Build a strong foundation in English vocabulary with our comprehensive courses.",
            "Learn English words effortlessly with our engaging and innovative course materials.",
            "Elevate your English language skills with our specialized word learning courses.",
            "Unleash your potential with our tailored English word learning programs.",
            "Develop a robust English vocabulary with our carefully crafted course content.",
            "Gain a deeper understanding of English words and their usage in context.",
            "Empower yourself with the knowledge of essential English words and phrases.",
            "Achieve your language learning goals with our proven English word courses.",
            "Maximize your learning outcomes with our personalized English word learning approach.",
            "Improve your English vocabulary systematically and efficiently with our courses.",
            "Discover effective strategies for memorizing and retaining English words.",
            "Transform your language skills with our engaging and interactive English word courses.",
            "Expand your English vocabulary and boost your confidence in communication.",
            "Experience the joy of learning with our captivating English word courses.",
            "Stay motivated and inspired on your journey to mastering English words.",
            "Learn English words in a fun and supportive learning environment.",
            "Discover the beauty and diversity of the English language through our courses.",
            "Stay engaged and motivated with our dynamic and interactive word learning activities.",
            "Achieve fluency in English vocabulary through our immersive learning experience.",
            "Master English words effortlessly with our proven learning methodologies.",
            "Experience accelerated learning with our innovative English word courses.",
            "Take your language skills to the next level with our comprehensive word learning program.",
            "Improve your English vocabulary with our practical and engaging course materials.",
            "Gain practical language skills that you can apply in real-world situations.",
            "Learn at your own pace with our flexible and self-paced English word courses.",
            "Stay motivated and on track with our supportive learning community.",
            "Discover the joy of learning with our engaging and interactive English word courses.",
            "Achieve your language learning goals faster with our focused word learning approach.",
            "Develop a solid foundation in English vocabulary with our structured courses.",
            "Enhance your English language skills with our expertly designed course curriculum.",
            "Experience personalized learning tailored to your individual needs and goals.",
            "Learn English words in context and improve your comprehension skills.",
            "Stay motivated and engaged with our interactive and engaging course materials.",
            "Achieve fluency in English vocabulary through regular practice and reinforcement.",
            "Experience the benefits of immersive language learning with our English word courses.",
            "Learn essential English words that are commonly used in everyday conversations.",
            "Develop confidence in your language skills through our practical word learning exercises.",
            "Gain a deeper appreciation for the nuances of the English language with our courses.",
            "Start your journey to English fluency today with our comprehensive word learning program."
    };

    public static String selectCourseTitle(int index) {
        return index >= TITLES.length ? TITLES[0] : TITLES[index];
    }

    public static String selectCourseDescription(int index) {
        return index >= DESCRIPTIONS.length ? DESCRIPTIONS[0] : DESCRIPTIONS[index];
    }
}
