spring:
  config:
    import: optional:secrets.properties
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 46294A404D635166546A576E5A7234753778214125442A472D4B615064526755
      expiration: 86400000 # DAY
      refresh-token:
        expiration: 604800000 # 7 DAYS